name: mvl_lint
description: Custom analyzer plugin with MVL lint rules.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.1

# Add regular dependencies here.
dependencies:
  analysis_server_plugin: ^0.3.16
  analyzer: ^13.1.0
  analyzer_plugin: ^0.14.10
  collection: ^1.19.1
  path: ^1.9.1

  _fe_analyzer_shared: any
dev_dependencies:
  analyzer_testing: ^0.3.0
  lints: ^6.0.0
  test: ^1.25.6
  test_reflective_loader: ^0.4.0
