name: mvl_lint
description: Custom analyzer plugin with MVL lint rules.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  analysis_server_plugin: any
  analyzer: any
  analyzer_plugin: any
  collection: any
  path: any

dev_dependencies:
  analyzer_testing: any
  test: any
  test_reflective_loader: any
